apiVersion: v1
kind: Service
metadata:
  name: dlf-loadbalancer-svc
  labels:
    run: dlf-loadbalancer-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort:   
    protocol: TCP
  selector:
    app: dfly
